# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_x": "00_core.ipynb",
         "get_y": "00_core.ipynb",
         "vocab": "00_core.ipynb",
         "patient_id_splitter": "00_core.ipynb",
         "build_DataBlock": "00_core.ipynb",
         "get_preds": "00_core.ipynb",
         "create_submission_csv": "00_core.ipynb"}

modules = ["pipeline.py"]

doc_url = "https://bwolfson.github.io/melanoma_classifier/"

git_url = "https://github.com/bwolfson/melanoma_classifier/tree/master/"

def custom_doc_links(name): return None
